name: Compilar ElvUI v14.03 Especial

on:
  workflow_dispatch: # Activa el botón manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de la versión v14.03
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: 'refs/tags/v14.03' # <-- Esto le ordena bajarse la 14.03 sin importar que tu fork esté en la última versión
          fetch-depth: 0

      - name: Empaquetar Addon (Inyectar librerías)
        uses: BigWigsMods/packager@v2

      - name: Subir archivo comprimido listo
        uses: actions/upload-artifact@v4
        with:
          name: ElvUI-v14.03-Listo
          path: ./.shadow-images/*.zip # Busca cualquier archivo .zip generado en la ruta del empaquetador
